services:
  - type: web
    name: tg-stream-proxy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: BOT_TOKEN
        sync: false
      - key: ALLOWED_USER_ID
        value: "0"
      - key: API_SECRET_TOKEN
        generateValue: true
      - key: BASE_URL
        sync: false
      - key: TELEGRAM_API_URL
        value: "https://api.telegram.org"
